2019-06-20 09:26:40,325 first_case.py--> setUp 20: INFO --->this is chrome
2019-06-20 09:27:01,172 first_case.py--> setUp 20: INFO --->this is chrome
2019-06-20 09:27:21,580 first_case.py--> setUp 20: INFO --->this is chrome
2019-06-20 09:27:29,034 connectionpool.py--> urlopen 30: WARNING --->Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025CED4A8470>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')': /session/f4e67a13e14f4c1354dcdb571ec1dfad/screenshot
2019-06-20 09:27:30,038 connectionpool.py--> urlopen 30: WARNING --->Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025CED4A8DA0>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')': /session/f4e67a13e14f4c1354dcdb571ec1dfad/screenshot
2019-06-20 09:27:31,041 connectionpool.py--> urlopen 30: WARNING --->Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025CED4A8860>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')': /session/f4e67a13e14f4c1354dcdb571ec1dfad/screenshot
